// <auto-generated />
namespace NetworkingProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SeedBookData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedBookData));
        
        string IMigrationMetadata.Id
        {
            get { return "202412141911473_SeedBookData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
